{
    "response": {
        "@id": "155caa26-722c-4c25-9783-e64b26df6958",
        "elapsedtime": "0",
        "quotes": {
            "quote": [
                {
                    "ask": "325.6800",
                    "ask_time": "00:00",
                    "asksz": "2",
                    "beta": "0.6403",
                    "bid": "324.6000",
                    "bid_time": "00:00",
                    "bidsz": "17",
                    "bidtick": "d",
                    "name": "TESLA INC",
                    "symbol": "TSLA",
                    "vl": "4215807"
                },
                {
                    "ask": "0.00",
                    "ask_time": "00:00",
                    "asksz": "0",
                    "beta": "0.2128",
                    "bid": "0.00",
                    "bid_time": "00:00",
                    "bidsz": "0",
                    "bidtick": "d",
                    "name": "KROGER CO (THE)",
                    "symbol": "KR",
                    "vl": "10935029"
                },
                {
                    "ask": "0.000",
                    "ask_time": "00:00",
                    "asksz": "0",
                    "beta": "0.5085",
                    "bid": "0.000",
                    "bid_time": "00:00",
                    "bidsz": "0",
                    "bidtick": "d",
                    "name": "AT&T INC",
                    "symbol": "T",
                    "vl": "19960503"
                },
                {
                    "ask": "0.00",
                    "ask_time": "00:00",
                    "asksz": "0",
                    "beta": "1.3172",
                    "bid": "0.00",
                    "bid_time": "00:00",
                    "bidsz": "0",
                    "bidtick": "d",
                    "name": "FORD MOTOR CO. (DE)",
                    "symbol": "F",
                    "vl": "17876156"
                },
                {
                    "ask": "0.00",
                    "ask_time": "00:00",
                    "asksz": "0",
                    "beta": "1.6682",
                    "bid": "0.00",
                    "bid_time": "00:00",
                    "bidsz": "0",
                    "bidtick": "d",
                    "name": "GENERAL MOTORS CO",
                    "symbol": "GM",
                    "vl": "4907093"
                },
                {
                    "ask": "0.00",
                    "ask_time": "00:00",
                    "asksz": "0",
                    "beta": "0.1163",
                    "bid": "0.00",
                    "bid_time": "00:00",
                    "bidsz": "0",
                    "bidtick": "d",
                    "name": "WAL-MART STORES, INC.",
                    "symbol": "WMT",
                    "vl": "5478682"
                },
                {
                    "ask": "0.00",
                    "ask_time": "00:00",
                    "asksz": "0",
                    "beta": "0.9048",
                    "bid": "0.00",
                    "bid_time": "00:00",
                    "bidsz": "0",
                    "bidtick": "d",
                    "name": "SYNCHRONY FINANCIAL",
                    "symbol": "SYF",
                    "vl": "4260019"
                },
                {
                    "ask": "195.05",
                    "ask_time": "00:00",
                    "asksz": "1",
                    "beta": "1.3785",
                    "bid": "194.86",
                    "bid_time": "00:00",
                    "bidsz": "1",
                    "bidtick": "d",
                    "name": "NVIDIA CORP",
                    "symbol": "NVDA",
                    "vl": "11656871"
                },
                {
                    "ask": "0.0000",
                    "ask_time": "00:00",
                    "asksz": "0",
                    "beta": "2.4344",
                    "bid": "0.0000",
                    "bid_time": "00:00",
                    "bidsz": "0",
                    "bidtick": "d",
                    "name": "ALIBABA GROUP HOLDING LTD",
                    "symbol": "BABA",
                    "vl": "12524722"
                },
                {
                    "ask": "0.0000",
                    "ask_time": "00:00",
                    "asksz": "0",
                    "beta": "0.8919",
                    "bid": "0.0000",
                    "bid_time": "00:00",
                    "bidsz": "0",
                    "bidtick": "d",
                    "name": "GENERAL ELECTRIC CO",
                    "symbol": "GE",
                    "vl": "46370351"
                },
                {
                    "ask": "175.190",
                    "ask_time": "00:00",
                    "asksz": "1",
                    "beta": "1.3075",
                    "bid": "174.970",
                    "bid_time": "00:00",
                    "bidsz": "1",
                    "bidtick": "d",
                    "name": "APPLE INC",
                    "symbol": "AAPL",
                    "vl": "16349444"
                },
                {
                    "ask": "0",
                    "ask_time": "na",
                    "asksz": "na",
                    "beta": "na",
                    "bid": "0",
                    "bid_time": "na",
                    "bidsz": "na",
                    "bidtick": "na",
                    "name": "NA",
                    "symbol": "RDS.A",
                    "vl": "na"
                },
                {
                    "ask": "0.00",
                    "ask_time": "00:00",
                    "asksz": "0",
                    "beta": "2.8848",
                    "bid": "0.00",
                    "bid_time": "00:00",
                    "bidsz": "0",
                    "bidtick": "d",
                    "name": "ZILLOW GROUP INC",
                    "symbol": "ZG",
                    "vl": "134208"
                },
                {
                    "ask": "85.59",
                    "ask_time": "00:00",
                    "asksz": "2",
                    "beta": "1.467",
                    "bid": "85.55",
                    "bid_time": "00:00",
                    "bidsz": "99",
                    "bidtick": "d",
                    "name": "MICROSOFT CORPORATION",
                    "symbol": "MSFT",
                    "vl": "14145841"
                },
                {
                    "ask": "0.00",
                    "ask_time": "00:00",
                    "asksz": "0",
                    "beta": "1.5372",
                    "bid": "0.00",
                    "bid_time": "00:00",
                    "bidsz": "0",
                    "bidtick": "d",
                    "name": "NORFOLK SOUTHERN CORP.",
                    "symbol": "NSC",
                    "vl": "578826"
                },
                {
                    "ask": "0.00",
                    "ask_time": "00:00",
                    "asksz": "0",
                    "beta": "0.6888",
                    "bid": "0.00",
                    "bid_time": "00:00",
                    "bidsz": "0",
                    "bidtick": "d",
                    "name": "EXXON MOBIL CORP",
                    "symbol": "XOM",
                    "vl": "10161447"
                },
                {
                    "ask": "0.00",
                    "ask_time": "00:00",
                    "asksz": "0",
                    "beta": "1.112",
                    "bid": "0.00",
                    "bid_time": "00:00",
                    "bidsz": "0",
                    "bidtick": "d",
                    "name": "CORNING INC",
                    "symbol": "GLW",
                    "vl": "2392696"
                },
                {
                    "ask": "10.5300",
                    "ask_time": "00:00",
                    "asksz": "89",
                    "beta": "2.9938",
                    "bid": "10.5000",
                    "bid_time": "00:00",
                    "bidsz": "8",
                    "bidtick": "d",
                    "name": "ADVANCED MICRO DEVICES, INC.",
                    "symbol": "AMD",
                    "vl": "50744495"
                },
                {
                    "ask": "0.0000",
                    "ask_time": "00:00",
                    "asksz": "0",
                    "beta": "1.6704",
                    "bid": "0.0000",
                    "bid_time": "00:00",
                    "bidsz": "0",
                    "bidtick": "d",
                    "name": "VISA INC",
                    "symbol": "V",
                    "vl": "6190062"
                }
            ]
        },
        "error": "Success"
    }
}